### ISSUE TITLE
Tutorials: General 

### ISSUE THREAD

**Issue by LuPaschen** [a-leks-icon/AIRAL#1]
- [x] Choose example file from DoReCo with CC-BY license 
- [x] Give proper citation for the dataset in tutorials README
- [x] Have a .py script containing all code from each tutorial (comment out lines with help() command)

**Comment by a-leks-icon** [comment]
* Replaced the Urum .eaf with an .eaf file from Teop.
* Cited the DoReCo database as well as the methods and the Teop database from DoReCo in the README files.
* Created a .py script for the second tutorial containing all code snippets.
