### ISSUE TITLE
Tutorials: 01 Corflow Basics

### ISSUE THREAD

**Issue by LuPaschen** [a-leks-icon/AIRAL#3]
- [x] briefly discuss why exported files may have different file sizes than the original file
- [x] Classes and Objects: new image
- [x] explanation of .struct attribute unclear, in the example .name produces the same output as .struct.name . suggestion: clarify output of tier, tier.struct, tier.struct.name. give example of use case for .struct attribute
- [x] Parents: .parent() breaks if a tier does not have a parent ("'NoneType' object has no attribute 'name'")
- [x] Children: "Both methods collect child objects regardless to which structure they belong to" and the code example / output is unclear

**Comment by a-leks-icon** [comment]
* Added a paragraph addressing the issue with exported .eaf files using Corflow.
* Replaced the old .png using a screenshot of an Urum .eaf with an .eaf from Teop.
* Extended the description of the `.struct` attribute and added a use case explaining when this attribute might be relevant for the user.
* Added code and comments explaining (1) how to check, if an object has either no parents or nor child objects, and (2) how to proceed in such cases.
